In [2]:
import numpy as np

### 1. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [2]:
import numpy

print("Creating 5X2 array using numpy.arange")
sampleArray = numpy.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


### 2. Write a NumPy program to create a 3x3x3 array filled with arbitrary values and find the minimum and maximum values.

In [3]:
import numpy as np
x = np.random.random((3, 3, 3))
print(x)

[[[0.88676596 0.94614689 0.60942518]
  [0.92390811 0.46710509 0.96557745]
  [0.54921653 0.80761003 0.07490555]]

 [[0.05267507 0.0624152  0.91257691]
  [0.20115882 0.03829689 0.02058361]
  [0.74649801 0.92124139 0.96437841]]

 [[0.72002258 0.73622145 0.78662705]
  [0.45904448 0.88936672 0.29557022]
  [0.47633943 0.00927397 0.44723958]]]


In [ ]:
import numpy as np

### 3. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [3]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### 4. Given an array
- arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9
- i) Extract all odd numbers from arr
- ii) Replace all odd numbers in arr with -1

In [4]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a[a % 2 == 1]


array([1, 3, 5, 7, 9])

### 5.Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0.

In [23]:
import numpy as np
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 6. Write a NumPy program to convert an array to a float type.

In [15]:
import numpy as np
import numpy as np
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


### 7. Write a NumPy program to generate five random numbers from the normal distribution.

In [16]:
import numpy as np
x = np.random.normal(size=5)
print(x)

[ 1.54634891 -2.15428224  0.33219843  0.4090311  -0.66034025]


### 8. Following is the input NumPy array delete column two and insert following new column in its place.
-sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94,66]]) newColumn = numpy.array([[10,10,10]])

In [8]:
import numpy

print("Printing Original array")
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = numpy.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = numpy.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = numpy.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


### 9. Write a NumPy program to compute the multiplication of two given matrices.

In [19]:
# Program to multiply two matrices using nested loops

# take a 3x3 matrix
A = [[12, 7, 3],
[4, 5, 6],
[7, 8, 9]]

# take a 3x4 matrix	
B = [[5, 8, 1, 2],
[6, 7, 3, 0],
[4, 5, 9, 1]]

result = [[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]]

# iterating by row of A
for i in range(len(A)):

# iterating by coloum by B
  for j in range(len(B[0])):

# iterating by rows of B
   for k in range(len(B)):
    result[i][j] += A[i][k] * B[k][j]

for r in result:
     print(r)


[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


### 10. Write a NumPy program to create a random vector of size 10 and sort it.

In [13]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.37547459 0.9943088  0.84169071 0.75858881 0.04434638 0.74639231
 0.48662143 0.80289011 0.36362025 0.55582599]
Sorted array:
[0.04434638 0.36362025 0.37547459 0.48662143 0.55582599 0.74639231
 0.75858881 0.80289011 0.84169071 0.9943088 ]


### 11. Write a NumPy program to compute the covariance matrix of two arrays.

In [14]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


### 12.Create a 4X2 integer array and Prints its :
-i)The shape of an array.
-ii) Array dimensions.
-iii) The Length of each element of the array in bytes

In [16]:
import numpy

firstArray = numpy.empty([4,2], dtype = numpy.uint16) 
print("Printing Array")
print(firstArray)

print("Printing numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)

Printing Array
[[    0     0]
 [    0 16368]
 [    0     0]
 [    0 16368]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


### 13. Write a NumPy program to concatenate element-wise two arrays of string.

In [17]:
import numpy as np
x1 = np.array(['Python', 'PHP'], dtype=np.str)
x2 = np.array([' Java', ' C++'], dtype=np.str)
print("Array1:")
print(x1)
print("Array2:")
print(x2)
new_array = np.char.add(x1, x2)
print("new array:")
print(new_array)

Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']
new array:
['Python Java' 'PHP C++']


### 14. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.

In [19]:
import numpy as np
x = np.array(['bansari', 'BJT', 'thakkar', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

Original Array:
['bansari' 'BJT' 'thakkar' 'C++']

Capitalized:  ['Bansari' 'Bjt' 'Thakkar' 'C++']
Lowered:  ['bansari' 'bjt' 'thakkar' 'c++']
Uppered:  ['BANSARI' 'BJT' 'THAKKAR' 'C++']
Swapcased:  ['BANSARI' 'bjt' 'THAKKAR' 'c++']
Titlecased:  ['Bansari' 'Bjt' 'Thakkar' 'C++']


### 15. Write a NumPy program to convert a given array into a list.

In [21]:
import numpy as np


arr = np.array([1, 2, 3])
print(f'NumPy Array:\n{arr}')

list1 = arr.tolist()
print(f'List: {list1}')

NumPy Array:
[1 2 3]
List: [1, 2, 3]


In [22]:
import numpy as np


arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f'NumPy Array:\n{arr}')

list1 = arr.tolist()

print(f'List: {list1}')

NumPy Array:
[[1 2 3]
 [4 5 6]]
List: [[1, 2, 3], [4, 5, 6]]


### 16. Write a NumPy program to compute the sum of all elements, sum of each column and sum of each row of a given array.

In [24]:
import numpy as np
x = np.array([[2,5],[7,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[2 5]
 [7 3]]
Sum of all elements:
17
Sum of each column:
[9 8]
Sum of each row:
[ 7 10]


### 17. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [25]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
print(y)


Original array: 
[[0.61276191 0.40495734 0.47431176 0.03196508]
 [0.23375809 0.49190837 0.33321024 0.69323948]
 [0.05917124 0.02524727 0.20555738 0.29829394]
 [0.75284163 0.79191245 0.2996078  0.13687289]
 [0.17097732 0.3751182  0.95813203 0.55161416]
 [0.68664553 0.89159251 0.66300688 0.65262553]
 [0.2762905  0.58293697 0.30238502 0.06708097]
 [0.11167798 0.36667643 0.12730032 0.44216338]
 [0.20695588 0.99507752 0.32359427 0.0920585 ]
 [0.08101604 0.03492484 0.46431083 0.55804574]]
First 5 rows of the above array:
[[0.61276191 0.40495734 0.47431176 0.03196508]
 [0.23375809 0.49190837 0.33321024 0.69323948]
 [0.05917124 0.02524727 0.20555738 0.29829394]
 [0.75284163 0.79191245 0.2996078  0.13687289]
 [0.17097732 0.3751182  0.95813203 0.55161416]]


### 18. Write a NumPy program to get the unique elements of a 1D and 2D array.

In [22]:
# import library
import numpy as np

# create 1d-array
arr = np.array([3, 3, 4,5, 6, 5,6, 4])

# find unique element
# from a array
rslt = np.unique(arr)

print(rslt)


# imoprt library
import numpy as np

# create a numpy 2d-array
arr = np.array([[9, 9, 7, 7],[3, 4, 3, 4]])

# find unique element
# from a array
rslt = np.unique(arr)

print(rslt)


[3 4 5 6]
[3 4 7 9]


### 19. Write a NumPy program to get the unique elements of an array.
- arr= [ -10 12.12 -0.2]

In [25]:
import numpy as np
x = np.array([-10, 12.12, -0.2])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))


Original array:
[-10.    12.12  -0.2 ]
Unique elements of the above array:
[-10.    -0.2   12.12]
Original array:
[-10.    12.12  -0.2 ]
Unique elements of the above array:
[-10.    -0.2   12.12]


### 20. Write a NumPy program to save a given array to a text file and load it. You have to save and load files using numpy library .

In [9]:
import numpy as np
import os
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
